service: fastapi-aria

provider:
  name: aws
  runtime: python3.11
  region: us-east-1

functions:
  app:
    handler: main.handler
    events:
      - httpApi: '*'

package:
  exclude:
    - venv/**
    - __pycache__/**
    - .pytest_cache/**
    - .git/**
    - node_modules/** 